name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      issues: read
      pull-requests: read
      discussions: read
      packages: read
      statuses: read
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: sunbos
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          config_octicon: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_identicons: yes
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_gists: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_sections: repositories
          plugin_lines_repositories_limit: 4
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_reactions: yes
          plugin_reactions_limit: 50
          plugin_reactions_details: percentage
          plugin_reactions_days: 30
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_sponsors: no
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 2
          plugin_repositories_starred: 4
          plugin_repositories_random: 2
          plugin_repositories_affiliations: owner, collaborator, organization_member
          plugin_repositories_forks: yes
